name: Java CI - BoardGame Catalog

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  validate-commits:
    name: Validar mensagens de commit (TAIGA-#)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validar commits (tem TAIGA-<n>)
        run: |
          git fetch origin main || true
          RANGE=$(git rev-list --no-merges origin/main..HEAD || git rev-list --no-merges HEAD^..HEAD)
          if [ -z "$RANGE" ]; then
            echo "Nenhum commit novo para checar."
            exit 0
          fi
          for c in $RANGE; do
            MSG=$(git log -1 --pretty=format:%B $c)
            echo "Commit $c -> $MSG"
            if ! echo "$MSG" | grep -qE '(TAIGA-[0-9]+|#[0-9]+)'; then
            echo "::error::Commit $c não possui referência Taiga (use TAIGA-<n> ou #<n>)."
            exit 1
          fi

          done

  build:
    name: Build e Testes
    runs-on: ubuntu-latest
    needs: validate-commits
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build (skip tests)
        run: mvn -B -DskipTests package
      - name: Run tests
        run: mvn -B test
      - name: Package
        run: mvn -B -DskipTests package
      - name: Upload artifact (JAR)
        uses: actions/upload-artifact@v3
        with:
          name: boardgame-catalog-jar
          path: target/*.jar
